# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/10628e2d-4eba-4f3c-a6f7-0e4bcffbb049";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9bed12f0-50f6-46e9-a7f2-17a1b8d20507";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/93408f2f-d9e6-41a8-b370-c6a48bd836a3";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/60ddd6db-f31a-4a5e-9f5b-fdb60e934515"; }
      { device = "/dev/zram0"; }
      { device = "/dev/zram2"; }
      { device = "/dev/zram3"; }
      { device = "/dev/zram1"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
